


INSERT INTO questions (question_status, question_title,equipment,question_text,question_photo,user_id) VALUES ('resolved','O2 analyzer not working','O2 generator','Inert gas — a gas or mixture of gases produced and distributed by inert gas system, containing insufficient oxygen to support the combustion of hydrocarbons. Before introducing the inert gas into the cargo tanks, it is important to maintain the oxygen content at 5% or less. This is to prevent the cargo from exploding. An oxygen analyzer has an important role in maintaining the safety aboard a gas carrier. When topping up inert gas into the cargo tanks, particular attention must be paid to maintain an oxygen content level of 5% or less in the inert gas supply. This is achieved by monitoring and recording the measurements displayed by the oxygen analyzer.','https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQB5QYoZ879lsCaSEMF-0LcPUl1bEm_1pOOmVIY1ympvO3c_wK6mg&s',3);

INSERT INTO questions (question_status, question_title,equipment,question_text,question_photo,user_id) VALUES ('open','O2 analyzer showing "LO" on screen','O2 generator','The device is not working when it is turned on; the alarm condition (red light) is activated and the power indicator (green light) is not illuminated.Limited oxygen flow and screen is showing "LO".','https://survitecgroup.com/media/339917/igg-display.jpg',2);

INSERT INTO questions (question_status, question_title,equipment,question_text,question_photo,user_id) VALUES ('resolved','White ring of residue inside IGG chamber','Kangrim IGG','Kangrim IGG problem with “white smoke” inside the IGG itself. After several years of use, the IGG develops problems of white smoke appearing inside the chamber. Is this normally the symptom that the inner chamber has cracked (water is coming into the burner trough)?','https://www.ravebo.nl/images/nieuws/scheepvaart/IGG_damage.jpg',1);

INSERT INTO questions (question_status, question_title,equipment,question_text,question_photo,user_id) VALUES ('open','Boiler not starting','Kangrim Boiler','Every engine room machinery system requires a specific procedure for starting and stopping it. Boiler being one of the most important systems on board ships, requires special care and attention during operation and maintenance. Inability to do so leads to major failures and accidents, which can not only be life-threatening but also cause huge damage to the ship’s properly.','https://img.nauticexpo.com/images_ne/photo-g/31209-6480267.jpg',1);

INSERT INTO questions (question_status, question_title,equipment,question_text,question_photo,user_id) VALUES ('open','My preaction system is not reaching the target nitrogen purity','Air Products N2 System','We test and configure our nitrogen generators to produce nitrogen gas with a purity of 98%. This process requires that the regulators inside the nitrogen generator be configured to maintain a certain pressure differential across the nitrogen separation membrane. If these regulators are adjusted in the field by non-qualified personnel, it could affect both the nitrogen purity and the nitrogen production rate, resulting in a reduction of nitrogen purity. To verify the purity of gas being produced, use a handheld gas analyzer connected to the sample port on the generator while it is running.','https://www.generon.com/wp-content/uploads/2017/07/chemical-tanker.jpg',3);

INSERT INTO questions (question_status, question_title,equipment,question_text,question_photo,user_id) VALUES ('open','How to use the trim optimisation','Kyma Shaft Power Meter','The vessel installed an auxiliary engine boiler to utilise the waste heat from the exhaust gas during port calls. Previously, only the exhaust gas waste heat from the main engine was utilised. The main engine would be shut off and the oil-fired boiler kept on. But this will not be as necessary onboard on these vessels. A Kyma shaft power meter and performance monitoring system was also specified. The loading computer has been installed with trim optimisation software to further support fuel efficiency.','https://www.igiantech.com/wp-content/uploads/2019/01/kyma-bg.jpg',2);

INSERT INTO questions (question_status, question_title,equipment,question_text,question_photo,user_id) VALUES ('open','What To Do During Marine Auxiliary Boiler’s Flame Failure or Fuel Pump Tripping?','Kangrim Boiler','One day the boiler shut down after flame failure alarm came.  After many futile attempts to restart the boiler on HFO, the boiler was changed over to diesel and manually fired. The auto firing mode was non operational and the FO pressure low alarm was coming and fuel pumps stopping. ','https://img.nauticexpo.com/images_ne/photo-g/31209-6480267.jpg',1);

INSERT INTO questions (question_status, question_title,equipment,question_text,question_photo,user_id) VALUES ('resolved','Stuck fuel rack','Main Engine','This is one of the most common problem with oil fired 2 stroke marine engines. The governor controls the fuel pump delivery through a fuel rack, which is a combination of mechanical links. Sometimes the fuel rack gets stuck leading to lack of fuel supply in the concerned unit which results in either fluctuation in the engine RPM if running or engine will not start from standstill.','https://www.marineinsight.com/wp-content/uploads/2014/03/MAN-BW-ME-GI-Engine.jpg',2);

INSERT INTO questions (question_status, question_title,equipment,question_text,question_photo,user_id) VALUES ('resolved','Boiler drum level control goes haywire','Aalborg Boiler','We are having 100 tones FBC boilers. Frequent problem observed is that whenever there is sudden load change the boiler drum level control goes haywire leading to tripping of boiler and turbine on drum level low or high. Our drum level control is 3-element control in auto mode.','https://www.marineinsight.com/wp-content/uploads/2012/09/boiler-marine.jpg',3);





INSERT INTO replies (replied_user_id,question_id,reply_text) VALUES (1,1,'Ship engineer has bypassed the N2 analyser and use the IG anaylser instead.');
INSERT INTO replies (user_id,question_id,reply_text) VALUES (2,1,'The scale is not able to use in N2 mode.');
INSERT INTO replies (replied_user_id,question_id,reply_text) VALUES (1,2,'How old is the vessel?');
INSERT INTO replies (replied_user_id,question_id,reply_text) VALUES (2,2,'She is 20 years old.');
INSERT INTO replies (replied_user_id,question_id,reply_text) VALUES (3,3,'This problem can be solved in 2 ways. If there are not so many cracks, doublers can be used. However, the best solution is to replace the cracked chamber, with a new updated one which has a thicker wall of 6mm instead of the standard 4mm. This is a large operation of about 5 working days of 12 Hrs, utilizing all the support from the ship’s crew, dockyard for lifting and delivering and to refit in place. It starts with removing all the upper and inner parts (filters) of the IGG chamber for lifting the top section. All the piping, electronic components and valves above the IGG have to be removed to make room for the lift. The chamber is approximately 3000 mm high, so in many occasions (this depends on how the vessel is built) in the upper deck a hole has to be cut in order to lift the chamber out of the IGG. If the space is made in the upper deck the inner chamber has to be hoisted up by chain hoist and removed.');
INSERT INTO replies (replied_user_id,question_id,reply_text) VALUES (2,4,'Almost all boilers come with an automation system of starting and stopping comprising of programmed pre-purging and post-purging of furnace before the burner is fired. Never ignore or isolate this safety feature. If the boiler has to run manually, it must be pre-purged by means of FD fan for at least 2 minutes. Avoiding this step can lead to blowback and even explosion.');
INSERT INTO replies (question_id) VALUES (5);
INSERT INTO replies (replied_user_id,question_id,reply_text) VALUES (1,6,'The Kyma KSP Trim Module has features to optimize vessel trim at any power and draft condition by use of KSP Logging history function and Trial mode.');
INSERT INTO replies (replied_user_id,question_id,reply_text) VALUES (3,7,'Try correcting pressure setting of the boiler: Generally the Fuel Oil pressure at the burner must be between 2 to 4 bars. In case the pressure is too high more fuel will be sent and the air fuel ratio disturbed. Less fuel pressure will give a lean mixture and flame will be unsteady and fail.');
INSERT INTO replies (replied_user_id,question_id,reply_text) VALUES (1,8,'All the mechanical links of the fuel rack must be well lubricated and greased before starting the main engine. If after starting the main engine, the engine rpm is constantly fluctuating even at lower speed in calm weather, check all the fuel rack as one or more of them must be stuck.');
INSERT INTO replies (replied_user_id,question_id,reply_text) VALUES (2,9,'The most common fault with a three-point level controller is the steam flow transmitter. Loosen the impulse pipes and cleanse the holes into the measuring orifice.');